name: Perform test database build and verification

on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        TANGOS_TESTING_DB_BACKEND: [sqlite]
    runs-on: ${{ matrix.os }}
    env:
      C: gcc-10
      CXX: g++-10
    steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/checkout@v2

    - name: Update python pip/setuptools/wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Build and install tangos
      run: |
        pip install -e .

    - name: Install latest pynbody
      run: python -m pip install pynbody

    - name: Install latest yt
      run: python -m pip install yt

    - name: Build test database
      working-directory: test_tutorial_build
      run: export INTEGRATION_TESTING=1; bash build.sh

    - uses: actions/upload-artifact@v2
      with:
        name: Tangos database
        path: test_tutorial_build/data.db

    - name: Verify database
      working-directory: test_tutorial_build
      run: |
        wget https://zenodo.org/record/10051592/files/reference_database.db?download=1 -O reference_database.db -nv
        tangos diff data.db reference_database.db --property-tolerance dm_density_profile 1e-2 0
      # --property-tolerance dm_density_profile here is because if a single particle crosses between bins
      # (which seems to happen due to differing library versions), the profile can change by this much
      #
      # previously had:
      # --ignore-value-of gas_map gas_map_faceon gas_map_sideon uvi_image uvi_image_sideon uvi_image_faceon
      # ignore-value-of above is a clunky fix for the use of 'approximate fast' images -- is it needed any longer?
